%% Exact linearization of the Simulink model transfer_function_review
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.10 and Simulink Control Design (TM) 5.7.
%
% Generated on: 16-Jul-2022 14:16:17

%% Specify the model name
model = 'transfer_function_signal_processing_example';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
bode(sys)

