function [pOpt, Info] = parameterEstimation_transfer_function_signal_processing_example(p)
%PARAMETERESTIMATION_TRANSFER_FUNCTION_SIGNAL_PROCESSING_EXAMPLE
%
% Solve a parameter estimation problem for the transfer_function_signal_processing_example model.
%
% The function returns estimated parameter values, pOpt,
% and estimation termination information, Info.
%
% The input argument, p, defines the model parameters to estimate,
% if omitted the parameters specified in the function body are estimated.
%
% Modify the function to include or exclude new experiments, or
% to change the estimation options.
%
% Auto-generated by SPETOOL on 16-Jul-2022 17:05:59.
%

%% Open the model.
open_system('transfer_function_signal_processing_example')

%% Specify Model Parameters to Estimate
%
if nargin < 1
    p = [];
end

%% Define the Estimation Experiments
%

Exp_1 = sdo.Experiment('transfer_function_signal_processing_example');

%%
% Specify the measured experiment output data.
Exp_1_Sig_Output = Simulink.SimulationData.Signal;
Exp_1_Sig_Output.Values    = getData('Exp_1_Sig_Output_Value');
Exp_1_Sig_Output.BlockPath = 'transfer_function_signal_processing_example/PS-Simulink Converter';
Exp_1_Sig_Output.PortType  = 'outport';
Exp_1_Sig_Output.PortIndex = 1;
Exp_1_Sig_Output.Name      = 'Vo';
Exp_1.OutputData = Exp_1_Sig_Output;

%%
% Specify experiment specific parameters.
Param = sdo.getParameterFromModel('transfer_function_signal_processing_example',{'C','R'});
Param(1).Value = 3.301075781668344e-05;
Param(1).Scale = 1.9073486328125e-06;
Param(2).Value = 226.7325960489042;
Param(2).Scale = 128;
Exp_1.Parameters = Param;

%%
% Create a model simulator from an experiment
Simulator = createSimulator(Exp_1);
%%
% Add experiment specific parameters/states to the list of parameters
% to estimate.
s = getValuesToEstimate(Exp_1);
p = [p; s];

%% Create Estimation Objective Function
%
% Create a function that is called at each optimization iteration
% to compute the estimation cost.
%
% Use an anonymous function with one argument that calls transfer_function_signal_processing_example_optFcn.
optimfcn = @(P) transfer_function_signal_processing_example_optFcn(P,Simulator,Exp_1);

%% Optimization Options
%
% Specify optimization options.
Options = sdo.OptimizeOptions;
Options.Method = 'patternsearch';
Options.MethodOptions.MaxIter = 1000;
Options.OptimizedModel = Simulator;

%% Estimate the Parameters
%
% Call sdo.optimize with the estimation objective function handle,
% parameters to estimate, and options.
[pOpt,Info] = sdo.optimize(optimfcn,p,Options);

%%
% Update the experiments with the estimated parameter values.
Exp_1 = setEstimatedValues(Exp_1,pOpt);

%% Update Model
%
% Update the model with the optimized parameter values.
sdo.setValueInModel('transfer_function_signal_processing_example',pOpt(1:0));
end

function Vals = transfer_function_signal_processing_example_optFcn(P,Simulator,Exp_1)
%TRANSFER_FUNCTION_SIGNAL_PROCESSING_EXAMPLE_OPTFCN
%
% Function called at each iteration of the estimation problem.
%
% The function is called with a set of parameter values, P, and returns
% the estimation cost, Vals, to the optimization solver.
%
% See the sdoExampleCostFunction function and sdo.optimize for a more
% detailed description of the function signature.
%

%%
% Define a signal tracking requirement to compute how well the model
% output matches the experiment data.
r = sdo.requirements.SignalTracking(...
    'RobustCost', 'on');
%%
% Update the experiment(s) with the estimated parameter values.
Exp_1 = setEstimatedValues(Exp_1,P);

%%
% Simulate the model and compare model outputs with measured experiment
% data.

F_r = 0;
Simulator = createSimulator(Exp_1,Simulator);
strOT = mat2str(Exp_1.OutputData(1).Values.Time);
Simulator = sim(Simulator, 'OutputOption', 'AdditionalOutputTimes', 'OutputTimes', strOT);

SimLog = find(Simulator.LoggedData,get_param('transfer_function_signal_processing_example','SignalLoggingName'));
Sig = find(SimLog,Exp_1.OutputData.Name);

Error = evalRequirement(r,Sig.Values,Exp_1.OutputData.Values);
F_r = F_r + Error;

%% Return Values.
%
% Return the evaluated estimation cost in a structure to the
% optimization solver.
Vals.F = F_r;
end

function Data = getData(DataID)
%GETDATA
%
% Helper function to store data used by parameterEstimation_transfer_function_signal_processing_example.
%
% The input, DataID, specifies the name of the data to retrieve. The output,
% Data, contains the requested data.
%

SaveData = load('parameterEstimation_transfer_function_signal_processing_example_Data');
Data = SaveData.Data.(DataID);
end
